### ISSUE TITLE
not a valid plugin but it seems minimum system requirements are met

### ISSUE THREAD

**Issue by rileyjrs** [utlib/CsvExport#10]
Hi -
After changing the name of the unzipped file directory from CsvExport-Master to CsvExport, we were able to install the plugin.

We would like to be able to do csv exports of transcribed data from our Omeka database with a Scripto plugin.  It appears the minimum system requirements for the CSV Export plugin by U of Toronto Libraries have been met as listed below, but the CsvExport option doesn't appear at the bottom of the collections or items pages.  Do you know what is wrong?

Omeka | 2.4.1
PHP | 7.0.21 (cgi-fcgi)
OS | Linux 3.2.61-grsec-modsign x86_64
MySQL Server | 5.6.34
MySQL Client | mysqlnd 5.0.12

Thanks

**Comment by dicksonlaw583** [comment]
The option appears as "csv" under "Output Formats", not "CsvExport". In addition, only Omeka 2.5+ supports export formats on the admin-side collections page due to a patch on Omeka's admin theme.

For diagnostic purposes, please provide a screenshot of the plugin screen (showing the plugin) and the bottom of the admin-side item listing view (showing "Output Formats"). Thank you.

**Comment by rileyjrs** [comment]
![screen_shot](https://user-images.githubusercontent.com/26339345/30571736-8a1f7648-9c9e-11e7-91ca-79bb952c7a45.jpg)
Hi -  thank you for letting me know to check under "output formats".  It still doesn't seem to be there, please see the screen shot.

**Comment by dicksonlaw583** [comment]
See the "csv" under "Output Formats"? That's the one.

**Comment by rileyjrs** [comment]
Ah -  thank you!  It was user error.  The export works.
